---
# For more information about handlers see:
# http://www.ansibleworks.com/docs/playbooks.html#handlers-running-operations-on-change
#

- name: restart newrelic
  service:
    name: newrelic-sysmond
    state: restarted
  when: newrelic_service_state != 'stopped'  and not ansible_unit_test
